
set $bg #272e33
set $fg #d3c6aa
set $accent #89b482
set $red #e67e80
set $bg_alt #374145

client.focused          $accent $accent $fg $accent $accent
client.focused_inactive $bg_alt $bg_alt $fg $bg_alt $bg_alt
client.unfocused        $bg_alt $bg_alt $fg $bg_alt $bg_alt
client.urgent           $red $red $fg $red $red
