
font_family JetBrains Mono
font_size 12.0

cursor #89b482
cursor_trail 3

background #272e33
foreground #d3c6aa

background_opacity 0.95

selection_background #89b482
selection_foreground #272e33

# base colors
color0 #272e33
color1 #e67e80
color2 #a7c080
color3 #dbbc7f
color4 #7fbbb3
color5 #d699b6
color6 #83c092
color7 #e6d5b8

# bright colors
color8 #374145
color9 #e67e80
color10 #a7c080
color11 #dbbc7f
color12 #7fbbb3
color13 #d699b6
color14 #83c092
color15 #d3c6aa

window_padding_width 15
